# -- How DNS records are synchronized between sources and providers; available values are `sync` & `upsert-only`.
policy: sync
# -- Specify the registry for storing ownership and labels.
# Valid values are `txt`, `aws-sd`, `dynamodb` & `noop`.
# If `noop` midaas manage all records on zone
registry: noop
# can restrict zone
provider:
  name: webhook
  webhook: 
    image: 
      repository: external-dns-midaas-webhook
      tag: dev
      pullPolicy: Always
    env:
    - name: GOFLAGS
      value: -buildvcs=false
    - name: TSIG_ZONE_${MIDAAS_ENV_KEYNAME}
      value: ${MIDAAS_ENV_KEYVALUE}
    - name: API_LOG_LEVEL
      value: DEBUG
    - name: PROVIDER_DNS_ZONE_SUFFIX
      value: ${MIDAAS_DEV_SUFFIX}
    - name: PROVIDER_WS_URL
      value: ${MIDAAS_WS_URL}
    - name: https_proxy
      value: ${https_proxy}
    - name: no_proxy
      value: .default,{no_proxy}
    extraVolumeMounts:
    - name: dev-workspace
      mountPath: /go/src/app
podSecurityContext:
  runAsNonRoot: false
extraVolumes:
- name: dev-workspace
  hostPath:
    path: /app

sources:
  - ingress
logLevel: debug