---
providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    namespaces:
      - default
      - ingress-traefik

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

service:
  type: ClusterIP